name: Release mosdns-x

on:
  workflow_dispatch:

jobs:

  build-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24
          check-latest: true
          cache: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build
        run: python ./release.py
        env:
          CGO_ENABLED: '0'
          VERSION: '1.2.3'

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: './release/mosdns*.zip'
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
